#!/usr/bin/env python3
"""Write ``schemas/request.schema.json``: the JSON Schema for request files.

The base is exported from the pydantic ``Request`` model, so it can never drift
from what the lint enforces. On top, every ``tool_id`` in use gets its own
``params`` schema fetched from the Tool Shed (see ``tool_schemas.py``) and
attached with ``if tool_id == <guid> then params must match``. Editors that
honour the ``# yaml-language-server: $schema=`` modeline use this file for
completion and inline errors, and the lint uses its ``$defs`` to check
``params`` without the network.

    python scripts/generate_schema.py            # (re)write, reusing committed $defs
    python scripts/generate_schema.py --refresh  # refetch every tool's schema
    python scripts/generate_schema.py --check --refresh   # CI: committed file == model + Tool Shed

``--check`` without ``--refresh`` reuses the committed ``$defs``, so it only
proves the model part and the set of tool_ids; with ``--refresh`` the tool
schemas are compared against what the Tool Shed serves today.
"""
import argparse
import json
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from request_models import Request, iter_request_files  # noqa: E402
from tool_schemas import (  # noqa: E402
    COMMITTED_SCHEMA,
    REPO_ROOT,
    SchemaResolver,
    SchemaSource,
    SchemaUnavailable,
    def_name,
    embed,
)

SCHEMA_ID = "https://raw.githubusercontent.com/galaxyproject/idc/main/schemas/request.schema.json"


def tool_ids_in_use() -> list[str]:
    guids = set()
    for path in iter_request_files():
        try:
            doc = yaml.safe_load(path.read_text())
        except yaml.YAMLError as exc:
            raise SystemExit(f"error: {path.relative_to(REPO_ROOT)}: invalid YAML: {exc}")
        if isinstance(doc, dict) and isinstance(doc.get("tool_id"), str):
            guids.add(doc["tool_id"])
    return sorted(guids)


def build_schema(guids: list[str], resolve: SchemaResolver) -> dict:
    base = Request.model_json_schema()
    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": SCHEMA_ID,
        "title": "IDC reference-data request",
        "description": (
            "One requested reference-data version: data-managers/<data_manager>/<version>.yaml. "
            "Generated by scripts/generate_schema.py - do not edit by hand."
        ),
        "type": "object",
        "additionalProperties": False,
        "properties": base["properties"],
        "required": base["required"],
    }
    defs = {}
    conditions = []
    for guid in guids:
        params_schema = resolve(guid)
        name = def_name(guid)
        defs[name] = embed(params_schema, name)
        conditions.append(
            {
                "if": {"properties": {"tool_id": {"const": guid}}, "required": ["tool_id"]},
                "then": {"properties": {"params": {"$ref": f"#/$defs/{name}"}}},
            }
        )
    if defs:
        schema["$defs"] = defs
        schema["allOf"] = conditions
    return schema


def render(schema: dict) -> str:
    return json.dumps(schema, indent=2, sort_keys=False) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="Exit 1 if the committed schema differs from a fresh one")
    parser.add_argument("--refresh", action="store_true", help="Refetch every tool's schema instead of reusing committed $defs")
    parser.add_argument("--output", type=Path, default=COMMITTED_SCHEMA)
    args = parser.parse_args(argv)

    resolve = SchemaSource(committed=None if args.refresh else args.output)
    try:
        schema = build_schema(tool_ids_in_use(), resolve)
    except SchemaUnavailable as exc:
        print(f"error: could not fetch a tool's parameter schema: {exc}", file=sys.stderr)
        return 1
    text = render(schema)
    rel = args.output.relative_to(REPO_ROOT) if args.output.is_relative_to(REPO_ROOT) else args.output

    if args.check:
        current = args.output.read_text() if args.output.is_file() else None
        if current != text:
            print(
                f"error: {rel} is stale - run `python scripts/generate_schema.py` and commit the result",
                file=sys.stderr,
            )
            return 1
        print(f"ok: {rel} is up to date ({len(schema.get('$defs', {}))} tool schema(s))")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text)
    print(f"wrote {rel} ({len(schema.get('$defs', {}))} tool schema(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
